update mappings to 1.19.3
re-added ClientPlayerInteractionManagerMixin, as RefinedCreativeInventory has not yet updated to 1.19.3.

Compiles, but crashes on world load with a NoSuchMethodError on PlayerScreenHandler$1Mixin